stages:
  - build_and_deploy

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_and_deploy:
  image: node:lts-alpine
  stage: build_and_deploy
  only:
    - master
  script:
    - export ENV=production
    - export NODE_ENV=production
    - export BUILD_PATH=dist
    - ./build/run-build
    - ./build/run
  tags:
    - production
