stages:
  - build
  - production

build_and_deploy:
  image: node:lts-alpine
  stage: build
  only:
    - master
  script:
    - export ENV=production
    - export NODE_ENV=production
    - export BUILD_PATH=dist
    - ./build/run-build
    - ./build/run
  tags:
    - gitlab-org-docker
