version: '3.6'

networks:
  default:
    external:
      name: network

services:
  vk-miniapp-nginx:
    container_name: vk-miniapp-nginx
    build:
      context: ./
      dockerfile: ./build/nginx/Dockerfile
    image: registry.gitlab.com/alias/vk-miniapp:nginx
    restart: 'always'
